### ISSUE TITLE
Undefined method PurchaseRequest::getCustomerReference()

### ISSUE THREAD

**Issue by dmaksimov** [hps/omnipay-heartland#4]
Getting an undefined method In AbstractPorticoRequest.php (line 307).

**Comment by slogsdon** [comment]
Thanks for the report, @dmaksimov! Does this still occur on the version we pushed out this morning?

**Comment by dmaksimov** [comment]
Looks like I installed it right before that commit was made. :)

It's working fine now. Thanks!

**Comment by slogsdon** [comment]
Awesome! Thanks for the confirmation. Let us know if you run into any issues moving forward.
