### ISSUE TITLE
Declined transaction coming through as successful

### ISSUE THREAD

**Issue by dmaksimov** [hps/omnipay-heartland#5]
Hi,

I was doing some testing with declined transactions and noticed that the payment response isSuccessful() would return as true even though the transaction has been declined.

**Comment by slogsdon** [comment]
@dmaksimov Apologies for the delay here! Somehow, your issue was missed originally, but #9 should correct this issue. We had another integrator run into this as well. Feel free to reopen if you're still experiencing issues.
